version: "3.9"

networks:
  mystore-network:
    driver: bridge

services:
  mystore-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
    ports:
      - "3306:3306"
    networks:
      - mystore-network

  mystore-api:
    image: mystore-api
    command: ["/app/wait-for-it.sh", "mystore-db:3306", "-t", "30", "--", "java", "-jar", "api.jar"]
    environment:
      DB_HOST: mystore-db
    ports:
      - "8080:8080"
    networks:
      - mystore-network
    depends_on:
      - mystore-db